version: "3.3"
services:
  app:
    build:
      context: src/main/java
      dockerfile: DockerFile_app
    container_name: backoffice
    restart: always
    image: backoffice_image
    ports:
      - 3000:8080